functions = require("lib.functions")

data:extend({
	{
		type = "fluid-wagon",
		name = "yir_wagon_tank_blue_small",
		icon = "__yi_railway__/graphics/icons/railway/4atw_fm1_icon.png",
		icon_size = 64,
		max_health = 400,
		capacity = 20000,
		collision_box = {{-0.6, -1.7}, {0.6, 1.7}},
		selection_box = {{-1, -2}, {1, 2}},
		vertical_selection_shift = -0.5,
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.3,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 3,
		energy_per_hit_point = 5,
	},
	{
		type = "fluid-wagon",
		name = "yir_wagon_tank_orange_small",
		icon = "__yi_railway__/graphics/icons/railway/4atw_fm1_icon.png",
		icon_size = 64,
		max_health = 400,
		capacity = 20000,
		collision_box = {{-0.6, -1.7}, {0.6, 1.7}},
		selection_box = {{-1, -2}, {1, 2}},
		vertical_selection_shift = -0.5,
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.3,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 3,
		energy_per_hit_point = 5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_zement_gray",
		icon = "__yi_railway__/graphics/icons/railway/cws64_zement_gray_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.3,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_zement_white",
		icon = "__yi_railway__/graphics/icons/railway/cws64_zement_white_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.3,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "yir_wagon2a_closed",
		icon = "__yi_railway__/graphics/icons/railway/wcs_closed_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_hopper_yellow",
		icon = "__yi_railway__/graphics/icons/railway/2a_hooper_y_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_corn_green",
		icon = "__yi_railway__/graphics/icons/railway/2a_corn_green_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_corn_blue",
		icon = "__yi_railway__/graphics/icons/railway/2a_corn_blue_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "yir_2acw_3blocks",
		icon = "__yi_railway__/graphics/icons/railway/2a_cws_tf1-icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.0,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "yir_2acw_wood",
		icon = "__yi_railway__/graphics/icons/railway/2a_cws_tf1-icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.0,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_tender_black",
		icon = "__yi_railway__/graphics/icons/railway/rtender_black_icon.png",
		icon_size = 64,
		inventory_size = 5,
		max_health = 400,
		collision_box = {{-0.6, -2.5}, {0.6, 2.1}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 2.5,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_tender_green",
		icon = "__yi_railway__/graphics/icons/railway/rtender_green_icon.png",
		icon_size = 64,
		inventory_size = 5,
		max_health = 400,
		collision_box = {{-0.6, -2.5}, {0.6, 2.1}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.15,
		air_resistance = 0.01,
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 2.5,
		energy_per_hit_point = 5,
		wheels = standard_wagon_wheels,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_trans",
		icon = "__yi_railway__/graphics/icons/railway/cws_trans_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_coal",
		icon = "__yi_railway__/graphics/icons/railway/cws_rcoal_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_copper",
		icon = "__yi_railway__/graphics/icons/railway/cws_rcopper_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_iron",
		icon = "__yi_railway__/graphics/icons/railway/cws_riron_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "y_wagon_stone",
		icon = "__yi_railway__/graphics/icons/railway/cws_rstone_icon.png",
		icon_size = 64,
		inventory_size = 20,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},
})