functions = require("lib.functions")

data:extend(
{
	{
		type = "fluid-wagon",
		name = "y_wagon_tank_fm1",
		icon = "__yi_railway__/graphics/icons/railway/4atw_fm1_icon.png",
		icon_size = 64,
		max_health = 600,
		capacity = 50000,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
	},

	{
		type = "fluid-wagon",
		name = "y_wagon_tank_fm2",
		icon = "__yi_railway__/graphics/icons/railway/4atw_fm2_icon.png",
		icon_size = 64,
		inventory_size = 0,
		max_health = 600,
		capacity = 50000,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
	},

	{
		type = "fluid-wagon",
		name = "yir_wagon_tank_orange",
		icon = "__yi_railway__/graphics/icons/railway/4a-fw-acid_icon.png",
		icon_size = 64,
		max_health = 600,
		capacity = 50000,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.4,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
	},

	{
		type = "fluid-wagon",
		name = "yir_wagon_tank_blue",
		icon = "__yi_railway__/graphics/icons/railway/4a-fw-blue_icon.png",
		icon_size = 64,
		capacity = 50000,
		max_health = 600,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
	},

	{
		type = "fluid-wagon",
		name = "yir_fw4a_tank_oil",
		icon = "__yi_railway__/graphics/icons/railway/4afw_oil_icon.png",
		icon_size = 64,
		max_health = 1000,
		capacity = 50000,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.55,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 8,
	},

	{
		type = "fluid-wagon",
		name = "yir_fw4_vc",
		icon = "__yi_railway__/graphics/icons/railway/4aw_fw_vc_icon.png",
		icon_size = 64,
		max_health = 1000,
		capacity = 50000,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		weight = 1000,
		max_speed = 2.0,
		braking_force = 2,
		friction_force = 0.4,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 8,
		resistances =
		{
			{type = "fire", decrease = 0, percent = 90},
			{type = "physical", decrease = 0, percent = 90},
			{type = "impact", decrease = 0, percent = 90},
			{type = "explosion", decrease = 0, percent = 90},
			{type = "acid", decrease = 0, percent = 90},
			{type = "laser", decrease = 0, percent = 70},
			{type = "electric", decrease = 0, percent = 70},
		},
		wheels = functions.standard_train_wheels,
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_purple",
		icon = "__yi_railway__/graphics/icons/railway/4a-kw-s1-icon.png",
		icon_size = 64,
		inventory_size = 10,
		max_health = 1000,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 2,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances =
		{
			{type = "fire", decrease = 0, percent = 90},
			{type = "physical", decrease = 0, percent = 90},
			{type = "impact", decrease = 0, percent = 90},
			{type = "explosion", decrease = 0, percent = 90},
			{type = "acid", decrease = 0, percent = 90},
			{type = "laser", decrease = 0, percent = 70},
			{type = "electric", decrease = 0, percent = 70},
		},

	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_oceanblue",
		icon = "__yi_railway__/graphics/icons/railway/4a-bw-s2-icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 500,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_grey",
		icon = "__yi_railway__/graphics/icons/railway/4a-tw-s3-icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 500,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_coal",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_coal_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_iron",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_iron_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_copper",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_copper_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_stone",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_stone_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_wood",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_wood_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_closed",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_closed_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_gold",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_gold_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_mun",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_mun_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_tf",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_tf_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_vc",
		icon = "__yi_railway__/graphics/icons/railway/4a-cw_vc_icon.png",
		icon_size = 64,
		inventory_size = 40,
		max_health = 1000, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 2.0,
		braking_force = 2,
		friction_force = 0.4,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances =
		{
			{type = "fire", decrease = 0, percent = 90},
			{type = "physical", decrease = 0, percent = 90},
			{type = "impact", decrease = 0, percent = 90},
			{type = "explosion", decrease = 0, percent = 90},
			{type = "acid", decrease = 0, percent = 90},
			{type = "laser", decrease = 0, percent = 70},
			{type = "electric", decrease = 0, percent = 70},
		},
		wheels = functions.standard_train_wheels,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
	},
})