--machines
data:extend({
   {
		type = "item",
		name = "yir_factory_stuff",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/factories/yir_fab_coins_icon.png",
		subgroup = "yir_workshop",
		order = "a",
		stack_size = 10,
		place_result = "yir_factory_stuff",
		weight = 1000000,
   },
   {
		type = "item",
		name = "yir_diesel_monument",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/yir_diesel_monument_icon.png",
		subgroup = "yir_workshop",
		order = "b",
		stack_size = 10,
		place_result = "yir_diesel_monument",
		weight = 1000000,
   },
   {
		type = "item",
		name = "yir_future_monument",
		icon = "__yi_railway__/graphics/icons/factories/yir_future_monument_icon.png",
		icon_size = 64,
		subgroup = "yir_workshop",
		order = "c",
		stack_size = 10,
		place_result = "yir_future_monument",
		weight = 1000000,
   },

   {
		type = "item",
		name = "yir_factory_loco",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/factories/yir_fac_loco_icon.png",
		subgroup = "yir_workshop",
		order = "f",
		stack_size = 10,
		place_result = "yir_factory_loco",
		weight = 100000,
   },
   {
		type = "item",
		name = "yir_factory_wagon",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/factories/yir_fac_waggon_icon.png",
		subgroup = "yir_workshop",
		order = "g",
		stack_size = 10,
		place_result = "yir_factory_wagon",
		weight = 100000,
   },
   {
		type = "item",
		name = "yir_factory_tiles",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/factories/yir_fac_tiles_icon.png",
		subgroup = "yir_workshop",
		order = "h",
		stack_size = 10,
		place_result = "yir_factory_tiles",
		weight = 100000,
   },
   {
		type = "item",
		name = "yir_factory_material",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/factories/yir_fac_parts_icon.png",
		subgroup = "yir_workshop",
		order = "d",
		stack_size = 10,
		place_result = "yir_factory_material",
		weight = 100000,
   },
   {
		type = "item",
		name = "yir_factory_chemical",
		icon = "__yi_railway__/graphics/icons/factories/chemie_32.png",
		icon_size = 64,
		subgroup = "yir_workshop",
		order = "e",
		stack_size = 10,
		place_result = "yir_factory_chemical",
		weight = 100000,
   },
})
--items
data:extend({
	{
		type = "item",
		name = "yir_coin",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/yir-coin-icon.png",
		subgroup = "yir_important",
		order = "a",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_diesel_coin",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/diesel_coin_icon.png",
		subgroup = "yir_important",
		order = "b",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_future_coin",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/future_coin_icon.png",
		subgroup = "yir_important",
		order = "c",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_fuel_coks",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/coks.png",
		subgroup = "yir_important",
		order = "d",
		stack_size = 30,
		fuel_value = "35MJ",
		fuel_category = "chemical",
	},
	{
		type = "item",
		name = "yir_fuel_diesel",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/diesel.png",
		subgroup = "yir_important",
		order = "e",
		stack_size = 50,
		hidden = true,
		fuel_value = "50MJ",
		fuel_category = "yr_diesel",
	},
	{
		type = "item",
		name = "yir_fuel_energy",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/fuel_cell_e.png",
		subgroup = "yir_important",
		order = "f",
		stack_size = 30,
		fuel_value = "40MJ",
		fuel_category = "chemical",
	},
	{
		type = "item",
		name = "yir_fuel_fluid_u3",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/fuel_gas.png",
		subgroup = "yir_important",
		order = "g",
		stack_size = 2500,
		hidden = true,
		fuel_value = "2MJ",
		fuel_category = "yr_diesel",
	},
	{
		type = "item",
		name = "yir_fuel_fluid_u2",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/fuel_light.png",
		subgroup = "yir_important",
		order = "h",
		stack_size = 2000,
		fuel_value = "1MJ",
		fuel_category = "yr_diesel",
	},
	{
		type = "item",
		name = "yir_fuel_fluid_u1",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/fuel_diesel.png",
		subgroup = "yir_important",
		order = "i",
		stack_size = 2500,
		hidden = true,
		fuel_value = "3MJ",
		fuel_category = "yr_diesel",
	},
	{
		type = "item",
		name = "yir_fuel_energy_u1",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/fuel_energy.png",
		subgroup = "yir_important",
		order = "j",
		stack_size = 2000,
		weight = 500,
		fuel_value = "2MJ",
		fuel_category = "yr_future",
	},

	{
		type = "item",
		name = "yir_lamp_old1",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/yir_lamp_old1_icon.png",
		subgroup = "yir_parts",
		order = "d1",
		stack_size = 10,
		place_result = "yir_lamp_old1",
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_lamp_clock",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/yir_clock_icon.png",
		subgroup = "yir_parts",
		order = "d2",
		stack_size = 10,
		place_result = "yir_lamp_clock",
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_lamp_modern",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/yir_lamp_modern_icon.png",
		subgroup = "yir_parts",
		order = "d3",
		stack_size = 10,
		place_result = "yir_lamp_modern",
		weight = 10000,
	},
})
--parts
data:extend({
	{
		type = "item",
		name = "yir_frame_loco_steam",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/frame_steam.png",
		subgroup = "yir_parts",
		order = "b1",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_frame_loco_diesel",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/frame_diesel.png",
		subgroup = "yir_parts",
		order = "b2",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_frame_loco_future",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/frame_future.png",
		subgroup = "yir_parts",
		order = "b3",
		stack_size = 10,
		weight = 10000,
	},

	{
		type = "item",
		name = "yir_frame_waggon",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/frame_wagon.png",
		subgroup = "yir_parts",
		order = "b4",
		stack_size = 10,
		weight = 10000,
	},

	{
		type = "item",
		name = "yir_radsatz_locos",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/radsatz_locomotive.png",
		subgroup = "yir_parts",
		order = "c1",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_radsatz_waggon",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/radsatz_waggon.png",
		subgroup = "yir_parts",
		order = "c2",
		stack_size = 10,
		weight = 10000,
	},

	{
		type = "item",
		name = "yir_color_white",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/paint_white.png",
		subgroup = "yir_parts",
		order = "a",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_color_green",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/paint_green.png",
		subgroup = "yir_parts",
		order = "a",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_color_black",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/paint_black.png",
		subgroup = "yir_parts",
		order = "a",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_color_blue",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/paint_blue.png",
		subgroup = "yir_parts",
		order = "a",
		stack_size = 10,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_color_red",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/paint_red.png",
		subgroup = "yir_parts",
		order = "a",
		stack_size = 10,
		weight = 10000,
	},
})
--tiles
data:extend({
	{
		type = "item",
		name = "y_tgb",
		icon = "__yi_railway__/graphics/path_tiles/floor_tplate.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "b[concrete]",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "y_tgb",
			condition_size = 3,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "y_tring",
		icon = "__yi_railway__/graphics/path_tiles/stripes.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "b[concrete]",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "y_tring",
			condition_size = 3,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "y_path_checker",
		icon = "__yi_railway__/graphics/path_tiles/labor_icon.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "b[concrete]",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "y_path_checker",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "y_path_science",
		icon = "__yi_railway__/graphics/path_tiles/vent_icon.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "b[concrete]",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "y_path_science",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "y_path_labor",
		icon = "__yi_railway__/graphics/path_tiles/floor004_icon.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "b[concrete]",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "y_path_labor",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "y_path_slag",
		icon_size = 32,
		icon = "__yi_railway__/graphics/path_tiles/pslag_icon.png",
		subgroup = "yir_tiles",
		hidden = true,
		order = "p0",
		stack_size = 100,
		weight = 10000,
	},
	{
		type = "item",
		name = "yir_brick1_tile",
		icon = "__yi_railway__/graphics/path_tiles/bricks_1.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "brick-1",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "yir_brick1_tile",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "yir_muster1_tile",
		icon = "__yi_railway__/graphics/path_tiles/muster-1.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "ground-3",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "yir_muster1_tile",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "yir_metal2_tile",
		icon_size = 32,
		icon = "__yi_railway__/graphics/path_tiles/metal_gitter.png",
		subgroup = "yir_tiles",
		order = "metal-2",
		stack_size = 100,
		weight = 10000,
		place_as_tile = {
			result = "yir_metal2_tile",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "yir_metal3_tile",
		icon_size = 32,
		icon = "__yi_railway__/graphics/path_tiles/metal_3.png",
		subgroup = "yir_tiles",
		order = "metal-3",
		stack_size = 100,
		weight = 10000,
		place_as_tile = {result = "yir_metal3_tile",
		condition_size = 2,
		condition = {layers={water_tile=true}}}
	},
	{
		type = "item",
		name = "yir_metal4_tile",
		icon_size = 32,
		icon = "__yi_railway__/graphics/path_tiles/metal_4.png",
		subgroup = "yir_tiles",
		order = "metal-4",
		stack_size = 100,
		weight = 10000,
		place_as_tile = {
			result = "yir_metal4_tile",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "yir_stony_tile",
		icon = "__yi_railway__/graphics/path_tiles/stony_icon.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "b[concrete]",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "yir_stony_tile",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},

	{
		type = "item",
		name = "yir_brick2_tile",
		icon = "__yi_railway__/graphics/path_tiles/bricks_2.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "brick-1",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "yir_brick2_tile",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},
	{
		type = "item",
		name = "yir_grating_tile",
		icon = "__yi_railway__/graphics/path_tiles/vent005_icon.png",
		icon_size = 32,
		subgroup = "yir_tiles",
		order = "b[concrete]",
		stack_size = 100,
		weight = 10000,
		place_as_tile =
		{
			result = "yir_grating_tile",
			condition_size = 2,
			condition = {layers={water_tile=true}}
		}
	},
})
--wagons
data:extend({
	{
		type = "item",
		name = "y_wagon_coal",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/cws_rcoal_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "a1",
		stack_size = 5,
		place_result = "y_wagon_coal",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_stone",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/cws_rstone_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "a2",
		stack_size = 5,
		place_result = "y_wagon_stone",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_iron",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/cws_riron_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "a3",
		stack_size = 5,
		place_result = "y_wagon_iron",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_copper",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/cws_rcopper_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "a4",
		stack_size = 5,
		place_result = "y_wagon_copper",
		weight = 200000,
	},

	{
		type = "item",
		name = "y_wagon_trans",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/cws_trans_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "b1",
		stack_size = 5,
		place_result = "y_wagon_trans",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_2acw_wood",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/cws_wood-icon.png",
		subgroup = "yir_cargowagons_small",
		order = "b2",
		stack_size = 5,
		place_result = "yir_2acw_wood",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_2acw_3blocks",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/2a_cws_tf1-icon.png",
		subgroup = "yir_cargowagons_small",
		order = "b3",
		stack_size = 5,
		place_result = "yir_2acw_3blocks",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_hopper_yellow",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/2a_hooper_y_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "b4",
		stack_size = 5,
		place_result = "y_wagon_hopper_yellow",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_wagon2a_closed",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/wcs_closed_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "b5",
		stack_size = 5,
		place_result = "yir_wagon2a_closed",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_corn_blue",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/2a_corn_blue_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "b6",
		stack_size = 5,
		place_result = "y_wagon_corn_blue",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_corn_green",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/2a_corn_green_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "b7",
		stack_size = 5,
		place_result = "y_wagon_corn_green",
		weight = 200000,
	},

	{
		type = "item",
		name = "y_wagon_zement_white",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/cws64_zement_white_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "d0",
		stack_size = 5,
		place_result = "y_wagon_zement_white",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_zement_gray",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/cws64_zement_gray_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "d0",
		stack_size = 5,
		place_result = "y_wagon_zement_gray",
		weight = 200000,
	},

	{
		type = "item",
		name = "y_wagon_tender_green",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/rtender_green_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "d1",
		stack_size = 5,
		place_result = "y_wagon_tender_green",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_tender_black",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/rtender_black_icon.png",
		subgroup = "yir_cargowagons_small",
		order = "d2",
		stack_size = 5,
		place_result = "y_wagon_tender_black",
		weight = 200000,
	},


	{
		type = "item",
		name = "yir_4acw_coal",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_coal_icon.png",
		subgroup = "yir_cargowagons",
		order = "a1",
		stack_size = 5,
		place_result = "yir_4acw_coal",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_stone",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_stone_icon.png",
		subgroup = "yir_cargowagons",
		order = "a2",
		stack_size = 5,
		place_result = "yir_4acw_stone",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_iron",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_iron_icon.png",
		subgroup = "yir_cargowagons",
		order = "a3",
		stack_size = 5,
		place_result = "yir_4acw_iron",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_copper",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_copper_icon.png",
		subgroup = "yir_cargowagons",
		order = "a4",
		stack_size = 5,
		place_result = "yir_4acw_copper",
		weight = 200000,
	},


	{
		type = "item",
		name = "yir_4acw_mun",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_mun_icon.png",
		subgroup = "yir_cargowagons",
		order = "b1",
		stack_size = 5,
		place_result = "yir_4acw_mun",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_wood",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_wood_icon.png",
		subgroup = "yir_cargowagons",
		order = "b2",
		stack_size = 5,
		place_result = "yir_4acw_wood",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_tf",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_tf_icon.png",
		subgroup = "yir_cargowagons",
		order = "b3",
		stack_size = 5,
		place_result = "yir_4acw_tf",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_gold",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_gold_icon.png",
		subgroup = "yir_cargowagons",
		order = "b4",
		stack_size = 5,
		place_result = "yir_4acw_gold",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_closed",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_closed_icon.png",
		subgroup = "yir_cargowagons",
		order = "b5",
		stack_size = 5,
		place_result = "yir_4acw_closed",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_purple",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4a-kw-s1-icon.png",
		subgroup = "yir_cargowagons",
		order = "b6",
		stack_size = 5,
		place_result = "yir_4acw_purple",
		weight = 200000,
	},
	{
		type = "item-with-entity-data",
		name = "yir_4acw_vc",
		icon = "__yi_railway__/graphics/icons/railway/4a-cw_vc_icon.png",
		subgroup = "yir_cargowagons",
		order = "b7",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_4acw_vc",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_grey",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4a-tw-s3-icon.png",
		subgroup = "yir_cargowagons",
		order = "c2",
		stack_size = 5,
		place_result = "yir_4acw_grey",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_4acw_oceanblue",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4a-bw-s2-icon.png",
		subgroup = "yir_cargowagons",
		order = "c2",
		stack_size = 5,
		place_result = "yir_4acw_oceanblue",
		weight = 200000,
	},


	{
		type = "item",
		name = "yir_fw4_vc",
		icon = "__yi_railway__/graphics/icons/railway/4aw_fw_vc_icon.png",
		icon_size = 64,
		subgroup = "yir_fluidwagons",
		order = "a",
		stack_size = 5,
		place_result = "yir_fw4_vc",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_tank_fm1",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4atw_fm1_icon.png",
		subgroup = "yir_fluidwagons",
		order = "b1",
		stack_size = 5,
		place_result = "y_wagon_tank_fm1",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_wagon_tank_fm2",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4atw_fm2_icon.png",
		subgroup = "yir_fluidwagons",
		order = "b2",
		stack_size = 5,
		place_result = "y_wagon_tank_fm2",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_wagon_tank_orange",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4a-fw-acid_icon.png",
		subgroup = "yir_fluidwagons",
		order = "c1",
		stack_size = 5,
		place_result = "yir_wagon_tank_orange",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_wagon_tank_blue",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/4a-fw-blue_icon.png",
		subgroup = "yir_fluidwagons",
		order = "c2",
		stack_size = 5,
		place_result = "yir_wagon_tank_blue",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_fw4a_tank_oil",
		icon = "__yi_railway__/graphics/icons/railway/4afw_oil_icon.png",
		subgroup = "yir_fluidwagons",
		order = "d",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_fw4a_tank_oil",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_wagon_tank_orange_small",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/wcs_tank_orange_icon.png",
		subgroup = "yir_fluidwagons",
		order = "e1",
		stack_size = 5,
		place_result = "yir_wagon_tank_orange_small",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_wagon_tank_blue_small",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/wcs_tank_blue_icon.png",
		subgroup = "yir_fluidwagons",
		order = "e2",
		stack_size = 5,
		place_result = "yir_wagon_tank_blue_small",
		weight = 200000,
	},
})
--locos
data:extend({
	{
		type = "item",
		name = "yir_loco_del_KR",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/kurts_icon.png",
		subgroup = "yir_loco_diesel2",
		order = "b-diesel-2",
		stack_size = 5,
		place_result = "yir_loco_del_KR",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_loco_del_mk1400",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/emd-gp_orange_icon.png",
		subgroup = "yir_loco_diesel2",
		order = "b-diesel-2",
		stack_size = 5,
		place_result = "yir_loco_del_mk1400",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_loco_de_bluegray",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/emd-gp_bluegray_icon.png",
		subgroup = "yir_loco_diesel2",
		order = "b-diesel-2",
		stack_size = 5,
		place_result = "yir_loco_de_bluegray",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_loco_sel_blue",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/rsea_blue_icon.png",
		subgroup = "yir_loco_steam",
		order = "a-steam-2",
		stack_size = 5,
		place_result = "yir_loco_sel_blue",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_fs_steam_green",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/rsea_green_icon.png",
		subgroup = "yir_loco_steam",
		order = "a-steam-2",
		stack_size = 5,
		place_result = "y_loco_fs_steam_green",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_emd3000_white",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/emd_gp_icon.png",
		subgroup = "yir_loco_diesel2",
		order = "b-diesel-2",
		stack_size = 5,
		place_result = "y_loco_emd3000_white",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_steam_wt450",
		icon = "__yi_railway__/graphics/icons/railway/sewt_bl_icon.png",
		subgroup = "yir_loco_steam",
		order = "a-steam-1",
		stack_size = 5,
		icon_size = 64,
		place_result = "y_loco_steam_wt450",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_loco_fut_red",
		icon = "__yi_railway__/graphics/icons/railway/future_red_icon.png",
		subgroup = "yir_loco_future",
		order = "c-electrical",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_loco_fut_red",
		weight = 200000,
	},


	{
		type = "item",
		name = "yir_loco_fesw_op",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/DESW90-OP-icon.png",
		subgroup = "yir_loco_future",
		order = "c-electrical",
		stack_size = 5,
		place_result = "yir_loco_fesw_op",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_emd1500black_v2",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/DESW90-BL-icon.png",
		subgroup = "yir_loco_diesel1",
		order = "b-diesel-1",
		stack_size = 5,
		place_result = "y_loco_emd1500black_v2",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_emd1500blue_v2",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/emd-1500_blue2_icon.png",
		subgroup = "yir_loco_diesel1",
		order = "b-diesel-1",
		stack_size = 5,
		place_result = "y_loco_emd1500blue_v2",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_emd1500black",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/emd-1500_black_icon.png",
		subgroup = "yir_loco_diesel1",
		order = "b-diesel-1",
		stack_size = 5,
		place_result = "y_loco_emd1500black",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_emd1500blue",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/emd-1500_blue_icon.png",
		subgroup = "yir_loco_diesel1",
		order = "b-diesel-1",
		stack_size = 5,
		place_result = "y_loco_emd1500blue",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_desw_orange",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/des_orange_icon.png",
		subgroup = "yir_loco_diesel1",
		order = "b-diesel-0",
		stack_size = 5,
		place_result = "y_loco_desw_orange",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_desw_blue",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/des_blue_icon.png",
		subgroup = "yir_loco_diesel1",
		order = "b-diesel-0",
		stack_size = 5,
		place_result = "y_loco_desw_blue",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_ses_std",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/sea-ss-icon.png",
		subgroup = "yir_loco_steam",
		order = "a-steam-0",
		stack_size = 5,
		place_result = "y_loco_ses_std",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_ses_red",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/sea-sr-icon.png",
		subgroup = "yir_loco_steam",
		order = "a-steam-0",
		stack_size = 5,
		place_result = "y_loco_ses_red",
		weight = 200000,
	},
	{
		type = "item",
		name = "y_loco_desw",
		icon_size = 64,
		icon = "__yi_railway__/graphics/icons/railway/des_green_icon.png",
		subgroup = "yir_loco_diesel1",
		order = "b-diesel-0",
		stack_size = 5,
		place_result = "y_loco_desw",
		weight = 200000,
	},
})